application: built-with-dart
version: 1
runtime: python27
api_version: 1
threadsafe: yes

pagespeed:
  enabled_rewriters:
    - InlineImages
    - CollapseWhitespace
    - RemoveComments
    - InlineJs

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.*\.png)
  static_files: static/\1
  expiration: 1d
  upload: static/(.*\.png)

- url: /(.*\.ico)
  static_files: static/\1
  expiration: 7d
  upload: static/(.*\.ico)

- url: /(.*\.jpg)
  static_files: static/\1
  expiration: 1d
  upload: static/(.*\.jpg)

- url: (.*)/
  static_files: static\1/index.html
  upload: static/index.html

- url: /
  static_dir: static

libraries:
- name: webapp2
  version: "2.5.1"
